"""RL training utilities."""

from .continuous_control import (
    ContinuousReplayBuffer,
    ContinuousTransitionBatch,
    DeterministicActor,
    SACAgent,
    SquashedGaussianActor,
    TD3Agent,
    TwinQCritic,
)
from .continuous_trainer import ContinuousConfig, ContinuousTrainer, train_continuous
from .dqn_agent import DQNAgent
from .dqn_model import DuelingQNetwork, LSTMQNetwork, QNetwork
from .env_adapter import (
    ContinuousActorPolicy,
    ContinuousTradingEnv,
    DQNPolicy,
    DiscreteActorPolicy,
    DiscreteTradingEnv,
    encode_observation,
)
from .on_policy_trainer import OnPolicyConfig, OnPolicyTrainer, train_on_policy as train_on_policy_legacy
from .plots import (
    PlotArtifacts,
    compute_symbol_diagnostics,
    ensure_zhang_eval_artifacts,
    generate_legacy_plots,
    generate_paper_style_plots,
    generate_rl_plots,
    generate_zhang_style_plots,
    load_daily_return_reports,
    load_zhang_contract_metrics,
    load_zhang_cost_sweep,
    load_zhang_portfolio_reports,
    plot_cumulative_returns,
    plot_symbol_diagnostics,
    plot_zhang_contract_diagnostics,
    plot_zhang_cost_sweep,
    plot_zhang_cumulative_trade_returns,
)
from .policy_gradient import (
    A2CAgent,
    CategoricalActor,
    OnPolicyBatch,
    PPOAgent,
    ValueCritic,
    compute_gae,
    discounted_return,
    discounted_reward_to_go,
)
from .production_a2c import ProductionA2CConfig, ProductionA2CTrainer
from .production_pg import ProductionPGConfig, ProductionPGTrainer
from .replay_buffer import ReplayBuffer, TransitionBatch
from .trainer import DQNConfig, DQNTrainer, TrainingArtifacts, load_or_build_features, train_dqn as train_dqn_legacy
from .zhang_eval import ZhangEvalArtifacts, ZhangEvalConfig, ZhangEvaluator, run_zhang_evaluation
from .zhang_production import (
    BASELINE_POLICIES,
    PRODUCTION_POLICIES,
    ProductionDatasetConfig,
    ProductionDQNConfig,
    ProductionRunArtifacts,
    ProductionSuiteConfig,
    WalkForwardConfig,
    WalkForwardWindow,
    _production_a2c_config,
    _production_dqn_config,
    prepare_production_dataset,
    run_production_suite,
    train_a2c_production,
    train_dqn_production,
    train_pg_production,
    validate_production_dataset,
)

train_dqn = train_dqn_production
train_on_policy = train_a2c_production

__all__ = [
    "DQNAgent",
    "DQNConfig",
    "DQNPolicy",
    "DQNTrainer",
    "A2CAgent",
    "CategoricalActor",
    "ContinuousActorPolicy",
    "ContinuousConfig",
    "ContinuousReplayBuffer",
    "ContinuousTradingEnv",
    "ContinuousTransitionBatch",
    "ContinuousTrainer",
    "DeterministicActor",
    "DiscreteActorPolicy",
    "DiscreteTradingEnv",
    "DuelingQNetwork",
    "LSTMQNetwork",
    "OnPolicyBatch",
    "OnPolicyConfig",
    "OnPolicyTrainer",
    "PPOAgent",
    "PlotArtifacts",
    "ProductionA2CConfig",
    "ProductionA2CTrainer",
    "ProductionDatasetConfig",
    "ProductionDQNConfig",
    "ProductionPGConfig",
    "ProductionPGTrainer",
    "ProductionRunArtifacts",
    "ProductionSuiteConfig",
    "QNetwork",
    "ReplayBuffer",
    "SACAgent",
    "SquashedGaussianActor",
    "TD3Agent",
    "TrainingArtifacts",
    "TransitionBatch",
    "TwinQCritic",
    "ValueCritic",
    "WalkForwardConfig",
    "WalkForwardWindow",
    "ZhangEvalArtifacts",
    "ZhangEvalConfig",
    "ZhangEvaluator",
    "BASELINE_POLICIES",
    "PRODUCTION_POLICIES",
    "compute_symbol_diagnostics",
    "compute_gae",
    "discounted_return",
    "discounted_reward_to_go",
    "ensure_zhang_eval_artifacts",
    "encode_observation",
    "generate_legacy_plots",
    "generate_paper_style_plots",
    "generate_rl_plots",
    "generate_zhang_style_plots",
    "load_or_build_features",
    "load_daily_return_reports",
    "load_zhang_contract_metrics",
    "load_zhang_cost_sweep",
    "load_zhang_portfolio_reports",
    "plot_cumulative_returns",
    "plot_symbol_diagnostics",
    "plot_zhang_contract_diagnostics",
    "plot_zhang_cost_sweep",
    "plot_zhang_cumulative_trade_returns",
    "prepare_production_dataset",
    "_production_a2c_config",
    "_production_dqn_config",
    "run_zhang_evaluation",
    "run_production_suite",
    "train_continuous",
    "train_dqn",
    "train_dqn_legacy",
    "train_on_policy",
    "train_on_policy_legacy",
    "train_a2c_production",
    "train_dqn_production",
    "train_pg_production",
    "validate_production_dataset",
]
