"""RL training utilities."""

from .continuous_control import (
    ContinuousReplayBuffer,
    ContinuousTransitionBatch,
    DeterministicActor,
    SACAgent,
    SquashedGaussianActor,
    TD3Agent,
    TwinQCritic,
)
from .continuous_trainer import ContinuousConfig, ContinuousTrainer, train_continuous
from .dqn_agent import DQNAgent
from .dqn_model import DuelingQNetwork, LSTMQNetwork, QNetwork
from .env_adapter import (
    ContinuousActorPolicy,
    ContinuousTradingEnv,
    DQNPolicy,
    DiscreteActorPolicy,
    DiscreteTradingEnv,
    encode_observation,
)
from .plots import (
    PlotArtifacts,
    compute_symbol_diagnostics,
    ensure_zhang_eval_artifacts,
    generate_legacy_plots,
    generate_paper_style_plots,
    generate_rl_plots,
    generate_zhang_style_plots,
    load_daily_return_reports,
    load_zhang_contract_metrics,
    load_zhang_cost_sweep,
    load_zhang_portfolio_reports,
    plot_cumulative_returns,
    plot_symbol_diagnostics,
    plot_zhang_contract_diagnostics,
    plot_zhang_cost_sweep,
    plot_zhang_cumulative_trade_returns,
)
from .policy_gradient import (
    A2CAgent,
    CategoricalActor,
    OnPolicyBatch,
    PPOAgent,
    ValueCritic,
    compute_gae,
    discounted_return,
    discounted_reward_to_go,
)
from .replay_buffer import ReplayBuffer, TransitionBatch
from .on_policy_trainer import OnPolicyConfig, OnPolicyTrainer, train_on_policy
from .trainer import DQNConfig, DQNTrainer, TrainingArtifacts, load_or_build_features, train_dqn
from .zhang_eval import ZhangEvalArtifacts, ZhangEvalConfig, ZhangEvaluator, run_zhang_evaluation

__all__ = [
    "DQNAgent",
    "DQNConfig",
    "DQNPolicy",
    "DQNTrainer",
    "A2CAgent",
    "CategoricalActor",
    "ContinuousActorPolicy",
    "ContinuousConfig",
    "ContinuousReplayBuffer",
    "ContinuousTradingEnv",
    "ContinuousTransitionBatch",
    "ContinuousTrainer",
    "DeterministicActor",
    "DiscreteActorPolicy",
    "DiscreteTradingEnv",
    "DuelingQNetwork",
    "LSTMQNetwork",
    "OnPolicyBatch",
    "OnPolicyConfig",
    "OnPolicyTrainer",
    "PPOAgent",
    "PlotArtifacts",
    "QNetwork",
    "ReplayBuffer",
    "SACAgent",
    "SquashedGaussianActor",
    "TD3Agent",
    "TrainingArtifacts",
    "TransitionBatch",
    "TwinQCritic",
    "ValueCritic",
    "ZhangEvalArtifacts",
    "ZhangEvalConfig",
    "ZhangEvaluator",
    "compute_symbol_diagnostics",
    "compute_gae",
    "discounted_return",
    "discounted_reward_to_go",
    "ensure_zhang_eval_artifacts",
    "encode_observation",
    "generate_legacy_plots",
    "generate_paper_style_plots",
    "generate_rl_plots",
    "generate_zhang_style_plots",
    "load_or_build_features",
    "load_daily_return_reports",
    "load_zhang_contract_metrics",
    "load_zhang_cost_sweep",
    "load_zhang_portfolio_reports",
    "plot_cumulative_returns",
    "plot_symbol_diagnostics",
    "plot_zhang_contract_diagnostics",
    "plot_zhang_cost_sweep",
    "plot_zhang_cumulative_trade_returns",
    "run_zhang_evaluation",
    "train_continuous",
    "train_dqn",
    "train_on_policy",
]
